# Generated by Django 4.0.4 on 2022-06-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(default='first name', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='last name', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='first_name',
            field=models.CharField(blank=True, default='first name', max_length=149),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='last_name',
            field=models.CharField(blank=True, default='last name', max_length=149),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='phone_number',
            field=models.IntegerField(blank=True, default='0729275511'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='profile_picture',
            field=models.ImageField(blank=True, default='image.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='website',
            field=models.URLField(max_length=30, null=True),
        ),
    ]
