# Generated by Django 4.0.4 on 2022-05-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='website',
            field=models.URLField(blank=True, max_length=199),
        ),
    ]
