# Generated by Django 4.0.4 on 2022-06-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='John55', max_length=30)),
                ('first_name', models.CharField(default='John', max_length=30)),
                ('last_name', models.CharField(default='Doe', max_length=30)),
                ('email', models.EmailField(default='john@gmail.com', max_length=30)),
                ('phone_number', models.IntegerField(null=True)),
                ('type', models.CharField(blank=True, default='wildlife', max_length=30)),
                ('country', models.CharField(blank=True, default='Kenya', max_length=30)),
                ('region', models.CharField(blank=True, default='Africa', max_length=30)),
            ],
        ),
    ]
