# Generated by Django 4.0.4 on 2022-07-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_b2ctransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2ctransaction',
            name='B2CChargesPaidAccountAvailableFunds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b2ctransaction',
            name='B2CRecipientIsRegisteredCustomer',
            field=models.CharField(choices=[(1, 'N'), (0, 'Y')], default=1, max_length=15),
        ),
        migrations.AddField(
            model_name='b2ctransaction',
            name='B2CUtilityAccountAvailableFunds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b2ctransaction',
            name='B2CWorkingAccountAvailableFunds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
