# Generated by Django 4.0.4 on 2022-05-31 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photographer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.photographer'),
            preserve_default=False,
        ),
    ]
