# Generated by Django 4.0.4 on 2022-07-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_b2ctransaction_b2cchargespaidaccountavailablefunds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2ctransaction',
            name='phone_number',
        ),
    ]
