# Generated by Django 4.0.4 on 2022-07-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_mpesacallbacks_mpesacalls_mpesapayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2CPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ResultDesc', models.TextField()),
                ('TransactionId', models.TextField()),
                ('TransactionReceipt', models.TextField()),
                ('TransactionAmount', models.IntegerField(max_length=10)),
                ('TransactionCompletedDateTime', models.TextField()),
                ('ReceiverPartyPubliName', models.TextField()),
            ],
            options={
                'verbose_name': 'B2C Payment',
                'verbose_name_plural': 'B2C Payments',
            },
        ),
    ]
