# Generated by Django 4.0.4 on 2022-05-31 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_event_photographer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photographer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.photographer'),
        ),
    ]
