# Generated by Django 4.0.4 on 2022-05-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_event_photographer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photos',
            field=models.ImageField(default='image.jpeg', upload_to=''),
        ),
    ]
