# Generated by Django 4.0.4 on 2022-05-31 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_event_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.photographer'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('photograher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.photographer')),
            ],
        ),
    ]
