# Generated by Django 4.0.4 on 2022-06-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_client_user_alter_photographer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='images',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='files',
            field=models.FileField(default='image.jpeg', upload_to=''),
        ),
    ]
