# Generated by Django 4.0.4 on 2022-06-20 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_portfolio_images_portfolio_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='files',
            new_name='file',
        ),
    ]
