# Generated by Django 4.0.4 on 2022-07-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_earnings_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='b2cpayment',
            old_name='ReceiverPartyPubliName',
            new_name='ReceiverPartyPublicName',
        ),
    ]
