# Generated by Django 4.0.4 on 2022-07-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_receiverpartypubliname_b2cpayment_receiverpartypublicname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='b2cpayment',
            old_name='ReceiverPartyPublicName',
            new_name='ReceiverPartyPubliName',
        ),
    ]
