# Generated by Django 4.0.4 on 2022-06-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_files_portfolio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='file',
            field=models.FileField(default='image.jpeg', upload_to='portfolio'),
        ),
    ]
