# Generated by Django 4.0.4 on 2022-06-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_portfolio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('file', models.FileField(default='image.jpeg', upload_to='homepage_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Watermarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('file', models.FileField(default='image.jpeg', upload_to='watermarks/')),
            ],
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='file',
            field=models.FileField(default='image.jpeg', upload_to='portfolio/'),
        ),
    ]
