# Generated by Django 4.0.4 on 2022-06-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_homepage_watermarks_alter_portfolio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='file',
            field=models.ImageField(default='image.jpeg', upload_to='homepage_photos/'),
        ),
        migrations.AlterField(
            model_name='watermarks',
            name='file',
            field=models.ImageField(default='image.jpeg', upload_to='watermarks/'),
        ),
    ]
