# Generated by Django 4.0.4 on 2022-06-01 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_doenloads_photographeraccount_downloads_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtphotos',
            name='transaction_number',
            field=models.CharField(max_length=70),
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='photos')),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=30)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.photographer')),
            ],
        ),
    ]
