# Generated by Django 4.0.4 on 2022-06-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_boughtphotos_transaction_number_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtphotos',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
