# Generated by Django 4.0.4 on 2022-06-23 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_rating_options_remove_rating_stars_rating_five_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={},
        ),
    ]
