# Generated by Django 4.0.4 on 2022-06-23 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_rating_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='five',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='four',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='one',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='photographer',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='three',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='two',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
