# Generated by Django 4.0.4 on 2022-06-23 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rating_five_rating_four_rating_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='app.photographer'),
        ),
    ]
